[settings]
debug_path = ./debug
image_path = ./images
script_path = ~/python3-idotmatrix-client/run_in_venv.sh
device_address = 99961A10-7BC3-D4BA-0C65-41334CA19A46
; latitude = -37.8136
; longitude = 144.9631
; timezone = Australia/Melbourne
latitude = 27.7676
longitude = -82.6403
timezone = America/New_York

; latitude = 29.7604
; longitude = -95.3698
; timezone = America/Chicago

frame_duration = 3000
update_interval = 1800

[weather]
api_url = https://api.open-meteo.com/v1/forecast?latitude={latitude}&longitude={longitude}&current_weather=true&timezone={timezone}&daily=sunrise,sunset&hourly=precipitation_probability